---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Mystery Letter
description: Create a mystery letter with lots of different styles.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Choose Your Message
- title: Editing Your Message
- title: Using Class Styles
- title: 'Challenge: Style Your Message'
- title: Editing Classes
- title: Create a New Class
- title: 'Challenge: Create A Computer Printout Style'
- title: 'Challenge: Create Your Own Styles'
